# -*- coding: utf-8 -*-
"""FSDS_bootcamp2_0_assignment_003_Oct_08.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/imshubhamk23/Python_Assignments/blob/main/FSDS_bootcamp2_0_assignment_003_Oct_08.ipynb

#1.Count the number of times iNeuron appears in the string
"""

text = "Welcome to iNeuron. You are a part of FSFS bootcamp 2.0 in iNeuron. I hope you are enjoying the  course in iNeuron"

print(text.count("iNeuron"))

"""# 2. Check if position 5 to 11 ends with the phrase iNeuron. in the string"""

txt = " Welcome to FSDS 2.0 at iNeuron "

txt[5:11] == "iNeuron" is True

# The result will be false position 5 to 11 does not end with the phrase iNeuron.

"""# 3. Write a program that takes your full name as input and displays the abbreviations of the first and middle names except the last name which is displayed as it is. For example, if your name is Sunny Bhaveen Chandra, then the output should be S.B.Chandra."""

name = "Shubham Suryakant Kolekar"

output = name[0] +"."+ name[8] +"."+ name[18:]

print(output)

"""#4. Join all items in a list into a string, using a hash(`#`) character as separator:
LIST = ["My", "name", "is", "Rishav", "Dash"]
"""

LIST = ["My", "name", "is", "Rishav", "Dash"]
"#".join(LIST)

"""#5. Write example for the following string manipulation function,

  ```
  - isdecimal()
  - islower()
  - isupper()
  - isalpha()
  - isnumeric()
"""

num = "25"
print(num.isdecimal())

a = "abcd"
print(a.islower())

a = "ABCD"
print(a.isupper())

a = "AbcD"
print(a.isalpha())

num = "123456"
print(num.isnumeric())

"""#6. Indian PAN card format follows the following formats - 
    - `AYEPC7894X`
    - `ABCDE9999Y`
# Take user input for PAN_CARD and validate as per the above example.
"""

pan_no = input("Enter Pan Number:- ")

if pan_no[0:5].isupper() and pan_no[5:9].isnumeric() and pan_no[-1].upper():
  print(f"The Pan number entered is:- {pan_no}")
else:
  print("Please enter valid Pan Number")